// Generated by Wrangler on Sat Aug 24 2024 13:48:08 GMT+0100 (British Summer Time)
// by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	DB: D1Database;
  TURNSTILE_SECRET_KEY: string;
}
